### PR TITLE
Fix broken symbols.svg template

### PR DESCRIPTION
**Pull request by fyrebase**
Currently the output when using symbols is a garbled mess. This fixes the output.

### CODE REVIEW

**Comment by GaryStanton** [comment]
+1. This fix worked for me.

**Comment by danielkorte** [comment]
This fix worked for me too. Thanks!

**Comment by dotmagic** [comment]
@soenkekluth Can you please merge this pull request? I need this fix urgent since svg symbols is the preferred way to integrated svg sprites.

**Comment by soenkekluth** [comment]
bit late sorry :) but its merged and published. 4.1.1

**Pull request merged**
