### PR TITLE
replace rust with lodash && remove libxmljs

### PR DESCRIPTION
**Pull request by soenkekluth**
up to date and now ready to install for everyone having problems with libxmljs

### CODE REVIEW

**Comment by soenkekluth** [comment]
@shakyShane `npm publish` please. 
currently svg-sprite-data version 3.0.0 isn't publish - thats why the test fails

**Comment by shakyShane** [comment]
This should be 4.0.0 - I have apps in production that are using 3.x

**Comment by shakyShane** [comment]
No worries I will sort

**Comment by soenkekluth** [comment]
gulp-svg-sprites is set to 4.0.0

**Comment by soenkekluth** [comment]
svg-sprite-data is set from 2.x to 3.0.0

**Comment by soenkekluth** [comment]
@shakyShane  see https://github.com/shakyShane/gulp-svg-sprites/blob/master/package.json
4.0.0

**Comment by soenkekluth** [comment]
everything should be fine ;)

**Comment by shakyShane** [comment]
both published 👍

**Comment by soenkekluth** [comment]
perfect!

**Comment by shakyShane** [comment]
Thanks for your time

**Comment by soenkekluth** [comment]
thanks for your work!

**Comment by soenkekluth** [comment]
will be going on and check if some features are needed or could be worth to implement... have a nice evening ;)

**Comment by shakyShane** [comment]
nice - also you may be able to close off some issues now related to libxml

**Comment by soenkekluth** [comment]
ok - i will take care of it!

**Pull request merged**
